version: "3"
services:
  jupyter-tensorflow2:
    build: .
    image: local/tensorflow-gpu
    #image: . tensorflow/tensorflow:2.15.0-gpu-jupyter
    volumes:
    - ./jupyter:/tf
    ports:
    - 8889:8888
    - 6007:6007
    container_name:   jupyter-tensorflow2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]