version: "3"
services:
  jupyter-tensorflow2-notebook2:
    image: tensorflow/tensorflow:2.15.0-jupyter
    volumes:
    - ./jupyter:/tf
    ports:
    - 8889:8888
    container_name:   jupyter-tensorflow2-notebook2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]